JavaScript 課題②  コードレビュー待機
tasakizawa/JSPractice1 pull request #5
Opened 2020-09-05 09:17 UTC by tasakizawa

2020-09-05 13:11 UTC, myzktkyk requested changes
動作を確認したのですが、正常に計算できる値を入れても何も表示されません。
指摘した点のうち `break` の typo と思われる部分からエラーが出てしまっている為と思われますので
修正のうえ、再度提出をお願いします。

2020-09-05 13:11 UTC, myzktkyk commented on JSPractice2-1-2.html
> +        breake;
おそらく `break` の Typo と思われますが… if 文の中で処理を切り上げる場合は `return` ですね。

2020-09-05 13:11 UTC, myzktkyk commented on JSPractice2-1-2.html
> +        document.write("エラー：整数を入力してください");
このやり方でエラー出力をするとテキストに添付されている `gif` と同じ動きになりません。

2020-09-05 13:11 UTC, myzktkyk commented on JSPractice2-1-2.html
> +      const newDiv = document.createElement("div");
これ以降の行のインデントが `while` と同じになってしまって
どこまでが `while` のブロックなのか見分けがつきません。
きちっとインデントしましょう。
エディターのショートカットで簡単にできますよ。

2020-09-05 21:36 UTC, tasakizawa commented on JSPractice2-1-2.html
> +        breake;
break→returnに修正しました。

2020-09-05 21:37 UTC, tasakizawa commented on JSPractice2-1-2.html
> +        document.write("エラー：整数を入力してください");
innerHTMLでの記述に修正しました。

2020-09-05 21:38 UTC, tasakizawa commented on JSPractice2-1-2.html
> +      const newDiv = document.createElement("div");
インデントを修正しました。

2020-09-06 01:27 UTC, niganium reviewed
お疲れ様です。アシスタントの西尾です。
指摘点の修正並びに要件通りの挙動を確認いたしました。
合格となります！以下細かい指摘点となります。

2020-09-06 01:27 UTC, niganium commented on JSPractice2-1-2.html
> +        if(fizzNum === buzzNum && fizzNum < 100 && buzzNum < 100) {
if構文にスペースを設けましょう。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/if...else

2020-09-06 01:27 UTC, niganium commented on JSPractice2-1-2.html
> +      while (fizzNum < 100 || buzzNum < 100) {
必須ではないですけど
以前やったfizzbuzzの判定に都度HTML要素を書き加えるような処理にしたらよりシンプルになりそうですね。
```
if (i % (fizzNum * buzzNum) === 0) {
  HTMLで書き出すような処理
} else if (i % fizzNum === 0) {
…
```

2020-09-06 07:39 UTC, merged